### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by mwaqar99** [ANTsX/ANTsRCore#116] opened 2020-03-29 12:10 UTC
Hello,

I can't seem to install ANTsRCore running:
- R 3.6.3
- With cmake/git installed
- OS X 10.14.5 (Mojave)

I've tried the the command line method as well as with binaries. The error seems to be with ANTsRCore on both occasions. Here is the error message using the command line method...am I doing something wrong??
--------------------------

* installing to library ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library’
* installing *source* package ‘ANTsRCore’ ...
** using staged installation
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
darwin18 1
-- Not using CCache
-- SuperBuild - ANTS => Requires ITKv5, 
-- SuperBuild -   ITKv5[OK]
-- SuperBuild - ANTS[OK]
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/user/Downloads/ANTsRCore/src/antb
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/libs/include/ITK-5.1/ -I/Users/user/Downloads/ANTsRCore/src -I/Users/user/Downloads/ANTsRCore/src/ants/Examples/include/   -I/Users/user/Downloads/ANTsRCore/src/ants/Utilities -I/Users/user/Downloads/ANTsRCore/src/ants/Examples/ -I../inst/include/   -I/Users/user/Downloads/ANTsRCore/src/ants/Tensor/  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c antsImageHeaderInfo.cpp -o antsImageHeaderInfo.o
In file included from antsImageHeaderInfo.cpp:6:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/libs/include/ITK-5.1/itkImageFileReader.h:173:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/libs/include/ITK-5.1/itkImageFileReader.hxx:29:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/libs/include/ITK-5.1/itksys/SystemTools.hxx:18:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:655:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/gethostuuid.h:39:17: error: 
      C++ requires a type specifier for all declarations
int gethostuuid(uuid_t, const struct timespec *) __OSX_AVAILABLE_STARTIN...
                ^
In file included from antsImageHeaderInfo.cpp:6:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/libs/include/ITK-5.1/itkImageFileReader.h:173:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/libs/include/ITK-5.1/itkImageFileReader.hxx:29:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/libs/include/ITK-5.1/itksys/SystemTools.hxx:18:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:662:27: error: 
      unknown type name 'uuid_t'; did you mean 'uid_t'?
int      getsgroups_np(int *, uuid_t);
                              ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_uid_t.h:31:31: note: 
      'uid_t' declared here
typedef __darwin_uid_t        uid_t;
                              ^
In file included from antsImageHeaderInfo.cpp:6:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/libs/include/ITK-5.1/itkImageFileReader.h:173:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/libs/include/ITK-5.1/itkImageFileReader.hxx:29:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/libs/include/ITK-5.1/itksys/SystemTools.hxx:18:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:664:27: error: 
      unknown type name 'uuid_t'; did you mean 'uid_t'?
int      getwgroups_np(int *, uuid_t);
                              ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_uid_t.h:31:31: note: 
      'uid_t' declared here
typedef __darwin_uid_t        uid_t;
                              ^
In file included from antsImageHeaderInfo.cpp:6:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/libs/include/ITK-5.1/itkImageFileReader.h:173:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/libs/include/ITK-5.1/itkImageFileReader.hxx:29:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/libs/include/ITK-5.1/itksys/SystemTools.hxx:18:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:727:31: error: 
      unknown type name 'uuid_t'; did you mean 'uid_t'?
int      setsgroups_np(int, const uuid_t);
                                  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_uid_t.h:31:31: note: 
      'uid_t' declared here
typedef __darwin_uid_t        uid_t;
                              ^
In file included from antsImageHeaderInfo.cpp:6:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/libs/include/ITK-5.1/itkImageFileReader.h:173:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/libs/include/ITK-5.1/itkImageFileReader.hxx:29:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/ITKR/libs/include/ITK-5.1/itksys/SystemTools.hxx:18:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:729:31: error: 
      unknown type name 'uuid_t'; did you mean 'uid_t'?
int      setwgroups_np(int, const uuid_t);
                                  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_uid_t.h:31:31: note: 
      'uid_t' declared here
typedef __darwin_uid_t        uid_t;
                              ^
5 errors generated.
make: *** [antsImageHeaderInfo.o] Error 1
ERROR: compilation failed for package ‘ANTsRCore’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ANTsRCore’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/ANTsRCore’

**Comment by muschellij2** [comment] 2020-03-29 17:08
Duplicate of https://github.com/ANTsX/ANTsRCore/issues/114.  Please look at previous issues before posting.  See https://github.com/RcppCore/Rcpp/issues/1046.  Solution: install github version of Rcpp, not from CRAN

**Closed by muschellij2** 2020-03-29 17:08 UTC

**Comment by mwaqar99** [comment] 2020-03-29 20:54
Many thanks this fixed the issue. Also your neuroconductor course and R packages are very good indeed!!
